
# Basic Configuration
name:               "Young H. Oh"
title:              "Ph.D. Candidates, SKKU ECE"
description:        ""
url:                http://younghwanoh.github.io
baseurl:            
markdown:           kramdown
highlighter:        rouge

gems:
- jekyll-paginate
paginate: 5
paginate_path: /news/page:num/

# Sass
sass:
    style:            :compressed


collections:
    images:
        output: true
